// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcyylF9XKDDYNm_1jSL-b9f6VR8oTbQZs',
    appId: '1:470422049887:web:4bc097cd11e644c679b7ea',
    messagingSenderId: '470422049887',
    projectId: 'seguridadciudadana-e8316',
    authDomain: 'seguridadciudadana-e8316.firebaseapp.com',
    storageBucket: 'seguridadciudadana-e8316.firebasestorage.app',
    measurementId: 'G-58HKR5SQ87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpKsRp2wS80R3izzwsUSXSyjNH51rPOpA',
    appId: '1:470422049887:android:ff5ac9739dc55fa579b7ea',
    messagingSenderId: '470422049887',
    projectId: 'seguridadciudadana-e8316',
    storageBucket: 'seguridadciudadana-e8316.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0vUa1Vf3AA8CYZ--iNrB2xPVItqXn9MI',
    appId: '1:470422049887:ios:ce5de50bc948112579b7ea',
    messagingSenderId: '470422049887',
    projectId: 'seguridadciudadana-e8316',
    storageBucket: 'seguridadciudadana-e8316.firebasestorage.app',
    iosBundleId: 'com.example.ciudadanoSeguroApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0vUa1Vf3AA8CYZ--iNrB2xPVItqXn9MI',
    appId: '1:470422049887:ios:ce5de50bc948112579b7ea',
    messagingSenderId: '470422049887',
    projectId: 'seguridadciudadana-e8316',
    storageBucket: 'seguridadciudadana-e8316.firebasestorage.app',
    iosBundleId: 'com.example.ciudadanoSeguroApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcyylF9XKDDYNm_1jSL-b9f6VR8oTbQZs',
    appId: '1:470422049887:web:b83b9215bc6cb2f579b7ea',
    messagingSenderId: '470422049887',
    projectId: 'seguridadciudadana-e8316',
    authDomain: 'seguridadciudadana-e8316.firebaseapp.com',
    storageBucket: 'seguridadciudadana-e8316.firebasestorage.app',
    measurementId: 'G-X8ZQ2FZ75Q',
  );
}
